In [17]:
import pandas as pd

In [2]:
import numpy as np

In [9]:
from collections import Counter

In [5]:
!ls

AffineNet.ipynb			   eai
BSpline.ipynb			   LoadStuff.ipynb
DefenseTransformationEvaluate.npz  Transformations.ipynb
DefenseTransformationSubmit.npz

In [7]:
eval_data = np.load(
    "DefenseTransformationEvaluate.npz"
)
print(eval_data["labels"], eval_data["representations"].shape)

submit_data = np.load("DefenseTransformationSubmit.npz")
print(submit_data["representations"].shape)

[7 8 5 ... 0 5 7] (5000, 192)
(20250, 192)

In [15]:
data = np.savez(
    "example_submission.npz",
    representations=np.random.rand(20250, 192),
)

In [19]:
# Translation [-3,3]
# Scale [2, 0.5]
# Rotation [0, 360]
# Reflection {-1, 1}
# Shear [-0.2, 0.2]

In [18]:
pd.DataFrame(submit_data["representations"]).describe()

,0,1,2,3,4,5,6,7,8,9,...,182,183,184,185,186,187,188,189,190,191
count,20250.000000,20250.000000,20250.000000,20250.000000,20250.000000,20250.000000,20250.000000,20250.000000,20250.000000,20250.000000,...,20250.000000,20250.000000,20250.000000,20250.000000,20250.000000,20250.000000,20250.000000,20250.000000,20250.000000,20250.000000
mean,-2.286544,0.627802,-1.593891,-0.972266,-2.218038,-5.674157,0.341854,-0.485760,2.329724,3.074423,...,4.518357,-0.277051,-6.580447,0.138534,-1.008249,3.123957,-3.091240,1.632462,-2.019135,5.144949
std,2.680790,3.352146,2.843847,2.289918,2.650157,2.880460,2.444140,2.806143,2.828111,2.656655,...,1.962607,3.063761,3.480632,2.658707,2.501902,4.011111,3.166257,2.805438,1.577401,3.454573
min,-12.411946,-13.059457,-12.171856,-10.771071,-12.343304,-15.890110,-9.517720,-11.376274,-10.907319,-7.126903,...,-8.422983,-12.857726,-16.630560,-11.777830,-11.923089,-17.903982,-14.704545,-10.586843,-8.792648,-11.477983
25%,-4.098731,-1.618677,-3.561482,-2.440830,-3.917543,-7.601987,-1.207941,-2.349120,0.475606,1.313080,...,3.367219,-2.399524,-9.127221,-1.628830,-2.712109,0.607082,-5.282691,-0.247578,-3.037162,2.905734
50%,-2.358671,0.658839,-1.696239,-0.980319,-2.206121,-5.764315,0.328912,-0.510158,2.493464,3.036201,...,4.647184,-0.368382,-6.967621,0.112597,-1.023366,3.499969,-3.322426,1.704826,-2.080067,5.360849
75%,-0.529549,2.843010,0.284268,0.498859,-0.540110,-3.875597,1.921359,1.363645,4.302840,4.784168,...,5.835205,1.799238,-4.420741,1.901454,0.699770,6.018104,-1.086229,3.588461,-1.091148,7.624704
max,11.149543,13.072227,11.596291,10.362783,11.257862,10.839200,9.340991,11.733546,12.377932,14.607908,...,11.654208,11.743513,10.279750,11.590203,8.915743,15.653210,9.848647,11.718102,7.348573,15.615421

In [ ]:
pd.submit_data["representations"]